Add Environment feature

diff --git a/package/generic/task b/package/generic/task
--- a/package/generic/task
+++ b/package/generic/task
@@ -1,6 +1,25 @@
-#!/bin/sh
+#!/bin/sh -u
 
-export DATA="$(dirname $0)/data"
-export TASK="$1"
+export FILEBOT_NODE_DATA="$(dirname $0)/data"
+export FILEBOT_NODE_TASK="$1"
 
-filebot @"$DATA/task/$TASK.args" >> "$DATA/log/$TASK.log" 2>&1
+
+# import user environment
+if [ -f "$FILEBOT_NODE_DATA/environment.sh" ]; then
+	source "$FILEBOT_NODE_DATA/environment.sh"
+fi
+
+
+# execute filebot task and record output
+filebot "@$FILEBOT_NODE_DATA/task/$FILEBOT_NODE_TASK.args" 2>&1 | tee -a "$FILEBOT_NODE_DATA/log/$FILEBOT_NODE_TASK.log"
+
+
+# get filebot exit code (and not tee exit code)
+STATUS="${PIPESTATUS[0]}"
+
+# treat ExitCode.NOOP as ExitCode.SUCCESS
+if [ $STATUS -eq 100 ]; then
+	exit 0
+fi
+
+exit $STATUS
